spring.datasource.url=${postgresql://youtube_tag_user:cP8LJuxlJ46k1ZdFjeZqENHdrfb8I45S@dpg-d9d10v741pts73dcdgi0-a/youtube_tag}
spring.datasource.username=${youtube_tag_user}
spring.datasource.password=${cP8LJuxlJ46k1ZdFjeZqENHdrfb8I45S}
spring.jpa.hibernate.ddl-auto=update
